version: '3.8'

services:

  log:
    container_name: ${LOGGING_HOST}
    image: log:latest
    restart: always
    volumes:
      - logging_data:/fluentd/log
      - ./config/dev/fluent.conf:/fluentd/etc/fluent.conf
    expose:
      - ${LOGGING_PORT}
      - "${LOGGING_PORT}/udp"
    networks:
      - internal

  write_model:
    container_name: ${WRITE_MODEL_DB_HOST}
    image: write_model:latest
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: ${WRITE_MODEL_POSTGRES_PASSWORD}
      POSTGRES_USER: ${WRITE_MODEL_POSTGRES_USER}
      POSTGRES_DB: ${WRITE_MODEL_POSTGRES_DB}
    expose:
      - "${WRITE_MODEL_DB_PORT}"
    logging:
      driver: "none"

  read_model:
    container_name: ${READ_MODEL_DB_HOST}
    image: read_model:latest
    networks:
      - internal
    environment:
      POSTGRES_PASSWORD: ${READ_MODEL_POSTGRES_PASSWORD}
      POSTGRES_USER: ${READ_MODEL_POSTGRES_USER}
      POSTGRES_DB: ${READ_MODEL_POSTGRES_DB}
    expose:
      - "${READ_MODEL_DB_PORT}"
    logging:
      driver: "none"

  migration:
    container_name: ${MIGRATION_HOST}
    image: migration:latest
    networks:
      - internal
    env_file:
      - ./dev.env
    expose:
      - ${MIGRATION_PORT}
    ports:
      - "${MIGRATION_PORT}:${MIGRATION_PORT}"


    # logging:
    #   driver: "none"
    volumes:
      - ./codebase:/application

  queue:
    container_name: ${Q_HOST}
    image: queue:latest
    networks:
      - internal
    # volumes:
    #   - ./log/rabbitmq/:/external/log/
    environment:
      RABBITMQ_NODENAME: 'rabbit@queue'
      RABBITMQ_NODE_PORT: ${Q_PORT}
      # RABBITMQ_LOGS: '/var/log/rabbitmq/rabbitmq.log'
    ports:
      - "${Q_EXT_ADMIN_PORT}:15672"
    expose:
      - ${Q_PORT}
    logging:
      driver: "none"


  read_model_sync:
    container_name: ${READ_MODEL_SYNC_HOST}
    image: read_model_sync:latest
    networks:
      - internal
    expose:
      - ${Q_PORT}
    env_file:
      - ./dev.env
    depends_on:
      - log
      - queue
      - read_model
      - migration
    logging:
      driver: "none"
    volumes:
      - ./codebase:/application

  # test:
  #   container_name: ${TEST_HOST}
  #   image: test:latest
  #   restart: always
  #   env_file:
  #     - ./dev.env
  #   expose:
  #     - "${TEST_PORT}"
  #   ports:
  #     - "${TEST_EXT_PORT}:${TEST_PORT}"
  #   networks:
  #     - internal
  #   depends_on:
  #     - log
  #     - write_model     
  #     - migration
  #   volumes:
  #     - ./codebase:/application

  # platform_new_pmt:
  #   container_name: ${PLATFORM_NEW_PMT_HOST}
  #   image: platform_new_pmt:latest
  #   restart: always
  #   env_file:
  #     - ./dev.env
  #   expose:
  #     - "${PLATFORM_NEW_PMT_PORT}"
  #   networks:
  #     - internal
  #   depends_on:
  #     - log
  #     - write_model     
  #     - queue
  #     - migration
  #   volumes:
  #     - ./codebase:/application


networks:
  internal:
    name: internal_network

volumes:
  logging_data: