version: '3.8'

services:

  log:
    container_name: ${LOGGING_HOST}
    image: log:latest
    restart: always
    volumes:
      - logging_data:/fluentd/log
      - ./config/dev/fluent.conf:/fluentd/etc/fluent.conf
    expose:
      - ${LOGGING_PORT}
      - "${LOGGING_PORT}/udp"
    networks:
      - receipt_network

  write_model:
    container_name: ${WRITE_MODEL_DB_HOST}
    image: write_model:latest
    networks:
      - receipt_network
    environment:
      POSTGRES_PASSWORD: ${WRITE_MODEL_POSTGRES_PASSWORD}
      POSTGRES_USER: ${WRITE_MODEL_POSTGRES_USER}
      POSTGRES_DB: ${WRITE_MODEL_POSTGRES_DB}
    expose:
      - "${WRITE_MODEL_DB_PORT}"
    ports:
      - "${WRITE_MODEL_DB_PORT}:${WRITE_MODEL_DB_EXT_PORT}"
    logging:
      driver: "none"

  read_model:
    container_name: ${READ_MODEL_DB_HOST}
    image: read_model:latest
    networks:
      - receipt_network
    environment:
      POSTGRES_PASSWORD: ${READ_MODEL_POSTGRES_PASSWORD}
      POSTGRES_USER: ${READ_MODEL_POSTGRES_USER}
      POSTGRES_DB: ${READ_MODEL_POSTGRES_DB}
    expose:
      - "${READ_MODEL_DB_PORT}"
    # ports:
    #   - "${READ_MODEL_DB_PORT}:${READ_MODEL_DB_EXT_PORT}"
    logging:
      driver: "none"

  queue:
    container_name: ${Q_HOST}
    image: queue:latest
    networks:
      - receipt_network
    # volumes:
    #   - ./log/rabbitmq/:/external/log/
    environment:
      RABBITMQ_NODENAME: 'rabbit@queue'
      RABBITMQ_NODE_PORT: ${Q_PORT}
      # RABBITMQ_LOGS: '/var/log/rabbitmq/rabbitmq.log'
    ports:
      - "${Q_EXT_ADMIN_PORT}:15672"
    expose:
      - ${Q_PORT}
    logging:
      driver: "none"

  migration:
    container_name: ${MIGRATION_HOST}
    image: migration:latest
    networks:
      - receipt_network
    env_file:
      - ./dev.env
    expose:
      - ${MIGRATION_PORT}
    logging:
      driver: "none"
    volumes:
      - ./codebase:/application

  read_model_sync:
    container_name: ${READ_MODEL_SYNC_HOST}
    image: read_model_sync:latest
    networks:
      - receipt_network
    expose:
      - ${Q_PORT}
    env_file:
      - ./dev.env
    depends_on:
      - log
      - queue
      - read_model
      - migration
    # logging:
    #   driver: "none"
    volumes:
      - ./codebase:/application

  # merchant_pos_new_checkout:
  #   container_name: ${MERCHANT_POS_NEW_CHECKOUT_HOST}
  #   image: merchant_pos_new_checkout:latest
  #   env_file:
  #     - ./dev.env
  #   expose:
  #     - "${MERCHANT_POS_NEW_CHECKOUT_PORT}"
  #   networks:
  #     - receipt_network
  #   depends_on:
  #     - log
  #     - write_model     
  #     - queue
  #     # - pmt_proc_new_pmt
  #     # - platform_new_receipt
  #   volumes:
  #     - ./codebase:/application




networks:
  receipt_network:
    name: receipt_network

volumes:
  logging_data: